### ISSUE TITLE
Profile becomes Null sometimes

### ISSUE THREAD

**Issue by djadifuntorum** [ninoprek/Jumanji-#110]
Application could have a null profile. 

PRIORITY: LOW

**Comment by aaronsum1102** [comment]
Added a check is the username is null, it will not show it. Since this is not a critical to operation and depend on network speed. Refer fab53a6104c3b034789b5fe198b9f6cc89b322f4

- [ ] to verify

**Comment by djadifuntorum** [comment]
Fix with commit https://github.com/ninoprek/Jumanji-/commit/1ff26322eac32618aa6c0591e2f22bdea4bb172d
