### ISSUE TITLE
Permission checking for storage

### ISSUE THREAD

**Issue by aaronsum1102** [ninoprek/Jumanji-#72]
Current runtime permission check execute when choice were made for taking photo, uploading existing and cancel. In the case where user choose to cancel, the run time permission checking should not start. Since no action will be performed for storage. 

If a user deny permission he/she will be presented with a dialog "Permission necessary", there is invisible button in the lover right corner of the dialogue. The button should be visible for the user to be aware and able to go to permissions.

When a user allow permission camera should start up, instead it is returned to the map screen and in order to take a picture user have to press the camera button again.

This is to improve user experience.

**Comment by djadifuntorum** [comment]
Verified on emulator with commit a10936f(Latest commit as of today)
. Works well already. Need to test on actual phone before closing this issue.

**Comment by djadifuntorum** [comment]
Confirmed fix with actual phone also with commit a10936f(Latest commit as of today)
