### ISSUE TITLE
Sign In Button

### ISSUE THREAD

**Issue by NemanjaIvkovic** [ninoprek/Jumanji-#89]
**Who:**
Sign In Button
**When:**
Button is available even if the data is not complete. It does not do anything until entered data is correct but it is not grayed out.
It can be confusing since button does nothing.
**Severity:**
High

**Comment by djadifuntorum** [comment]
Fix already in this commit https://github.com/ninoprek/Jumanji-/commit/0fb13a6966656194f7ca25ae0e3557bce5ddd7aa
