### ISSUE TITLE
Permission checking for Location

### ISSUE THREAD

**Issue by NemanjaIvkovic** [ninoprek/Jumanji-#90]
If a user deny permission he/she will be presented with a dialog "Permission necessary", there is invisible button in the lover right corner of the dialogue. The button should be visible for the user to be aware and able to go to permissions.

**Comment by djadifuntorum** [comment]
Fix already in this commit https://github.com/ninoprek/Jumanji-/commit/0fb13a6966656194f7ca25ae0e3557bce5ddd7aa
