### ISSUE TITLE
User location not in center of the screen

### ISSUE THREAD

**Issue by NemanjaIvkovic** [ninoprek/Jumanji-#91]
When user presses locate button sometimes it is shown somewhere off center of the screen.

**Severity:**
Low

**Comment by aaronsum1102** [comment]
1) This is hard to replicate. The locate button use last know position to position the map camera.
2) fix bug in save camera state, refer to 6da2df5cf52a53b843eed05223c0131f79ffd23f. The camera state of the map will be saved when it is out of view. 

- [ ] to verify

**Comment by djadifuntorum** [comment]
Verified on emulator with commit a10936f
. Works well already. Need to test on actual phone before closing this issue.

**Comment by djadifuntorum** [comment]
Verified on actual phone also with commit a10936f.
