### ISSUE TITLE
Null user

### ISSUE THREAD

**Issue by NemanjaIvkovic** [ninoprek/Jumanji-#93]
**Who:**
User field in profile tab

**When:**
When user is not signed in user field in the profile tab is showing "null", also when pressed Sign Out button toast appears saying "null, you are signed out."

**Severity:**
Low

**Comment by djadifuntorum** [comment]
Fix with this commithttps://github.com/ninoprek/Jumanji-/commit/0fb13a6966656194f7ca25ae0e3557bce5ddd7aa
